module.exports = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 11,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 2,
    spoonacularScore: 74,
    healthScore: 27,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 81.67,
    id: 633185,
    title: 'Awesome! No Bake ~ Macaroni and Cheese',
    readyInMinutes: 45,
    servings: 16,
    sourceUrl: 'http://www.foodista.com/recipe/DJBXLXPJ/awesome-no-bake-macaroni-and-cheese',
    image: 'https://spoonacular.com/recipeImages/633185-312x231.jpg',
    imageType: 'jpg',
    summary: 'You can never have too many side dish recipes, so give Awesome! No Bake ~ Macaroni and Cheese a try. This recipe serves 16 and costs 82 cents per serving. One serving contains <b>338 calories</b>, <b>11g of protein</b>, and <b>21g of fat</b>. Only a few people made this recipe, and 2 would say it hit the spot. A mixture of ketchup, you favorite macaroni, cottage cheese, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 76%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/macaroni-and-cheese-home-made-macaroni-and-cheese-is-a-comfort-food-that-is-hard-to-beat-you-can-put-away-the-pre-packaged-macaroni-and-cheese-at-the-store-600947">Macaroni and Cheese – home made macaroni and cheese is a comfort food that is hard to beat. You can put away the pre packaged macaroni and cheese at the store</a>, <a href="https://spoonacular.com/recipes/no-bake-macaroni-cheese-695678">No-Bake Macaroni & Cheese</a>, and <a href="https://spoonacular.com/recipes/macaroni-cheese-bake-429937">Macaroni & Cheese Bake</a> for similar recipes.',
    cuisines: [ 'American' ],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [],
    occasions: [],
    analyzedInstructions: [ [Object] ],
    spoonacularSourceUrl: 'https://spoonacular.com/awesome-no-bake-macaroni-and-cheese-633185'
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 1,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 61,
    healthScore: 21,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 87.32,
    id: 1095892,
    title: 'Vegan Green Bean Casserole',
    readyInMinutes: 60,
    servings: 6,
    sourceUrl: 'https://www.foodista.com/recipe/2M3K34BV/green-bean-casserole-vegan',
    image: 'https://spoonacular.com/recipeImages/1095892-312x231.jpg',
    imageType: 'jpg',
    summary: `The recipe Vegan Green Bean Casserole is ready <b>in about 1 hour</b> and is definitely an awesome <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> option for lovers of American food. For <b>87 cents per serving</b>, this recipe <b>covers 12%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains around <b>5g of protein</b>, <b>3g of fat</b>, and a total of <b>110 calories</b>. This recipe serves 6. It will be a hit at your <b>Thanksgiving</b> event. This recipe from Foodista requires nutritional yeast, water, onion, and extra-virgin olive oil. 1 person were glad they tried this recipe. It works well as a very reasonably priced hor d'oeuvre. Overall, this recipe earns a <b>solid spoonacular score of 71%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/vegan-green-bean-casserole-589324">Vegan Green Bean Casserole</a>, <a href="https://spoonacular.com/recipes/vegan-green-bean-casserole-624815">Vegan Green Bean Casserole</a>, and <a href="https://spoonacular.com/recipes/vegan-green-bean-casserole-1397921">Vegan Green Bean Casserole</a>.`,
    cuisines: [ 'American' ],
    dishTypes: [
      'side dish',
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [ 'fall', 'thanksgiving', 'winter' ],
    analyzedInstructions: [ [Object] ],
    spoonacularSourceUrl: 'https://spoonacular.com/vegan-green-bean-casserole-1095892'
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 5,
    gaps: 'no',
    lowFodmap: false,
    preparationMinutes: 5,
    cookingMinutes: 35,
    aggregateLikes: 0,
    spoonacularScore: 58,
    healthScore: 15,
    creditsText: 'Jen West',
    sourceName: 'Pink When',
    pricePerServing: 81.27,
    id: 1416203,
    title: 'Tater Tot Chili Cheese Casserole',
    readyInMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.pinkwhen.com/tater-tot-chili-cheese-casserole/',
    image: 'https://spoonacular.com/recipeImages/1416203-312x231.jpg',
    imageType: 'jpg',
    summary: `The recipe Tater Tot Chili Cheese Casserole can be made <b>in around 40 minutes</b>. Watching your figure? This gluten free recipe has <b>171 calories</b>, <b>6g of protein</b>, and <b>10g of fat</b> per serving. For <b>81 cents per serving</b>, this recipe 
<b>covers 10%</b> of your daily requirements of vitamins and minerals. This recipe serves 6. It works well as an American hor d'oeuvre. 
It will be a hit at your <b>The Super Bowl</b> event. 1 person were impressed by this recipe. It is brought to you by Pink When. A mixture of chili, tater tots, cheddar cheese, and a handful of other ingredients are all it takes to make this recipe so delicious. All things considered, we decided this recipe <b>deserves a spoonacular score of 0%</b>. This score is improvable. <a href="https://spoonacular.com/recipes/chili-cheese-tater-tot-casserole-688250">Chili Cheese Tater Tot Casserole</a>, <a href="https://spoonacular.com/recipes/chili-tater-tot-casserole-138065">Chili Tater Tot Casserole</a>, and <a href="https://spoonacular.com/recipes/tater-tot-casserole-aka-tater-tot-hotdish-713801">Tater Tot Casserole (aka Tater Tot Hotdish)</a> are very similar to this recipe.`,
    cuisines: [ 'American' ],
    dishTypes: [
      'side dish',
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [ 'gluten free' ],
    occasions: [ 'super bowl', 'fall', 'winter' ],
    analyzedInstructions: [ [Object], [Object] ],
    spoonacularSourceUrl: 'https://spoonacular.com/tater-tot-chili-cheese-casserole-1416203'
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 16,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 50,
    healthScore: 13,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 68.86,
    id: 646890,
    title: 'Home-Made Baked Corn Dogs + Vegan Version',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/43SL6B4C/home-made-baked-corn-dogs-vegan-version',
    image: 'https://spoonacular.com/recipeImages/646890-312x231.jpg',
    imageType: 'jpg',
    summary: `Home-Made Baked Corn Dogs + Vegan Version might be just the <b>American</b> recipe you are searching for. This hor d'oeuvre has <b>507 calories</b>, <b>17g of protein</b>, and <b>17g of fat</b> per serving. This recipe serves 4 and costs 69 cents per serving. This recipe from Foodista has 1 fans. Head to the store and pick up baking soda, , water, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. With a spoonacular <b>score of 49%</b>, this dish is solid. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/home-made-apple-butter-with-baked-brie-523639">Home Made Apple Butter with Baked Brie</a>, <a href="https://spoonacular.com/recipes/baked-corn-dogs-136170">Baked Corn Dogs</a>, and <a href="https://spoonacular.com/recipes/baked-corn-dogs-568330">Baked corn dogs</a>.`,
    cuisines: [ 'American' ],
    dishTypes: [
      'fingerfood',   'lunch',
      'antipasti',    'main course',
      'starter',      'snack',
      'appetizer',    'main dish',
      'antipasto',    'dinner',
      "hor d'oeuvre"
    ],
    diets: [],
    occasions: [],
    analyzedInstructions: [ [Object] ],
    spoonacularSourceUrl: 'https://spoonacular.com/home-made-baked-corn-dogs-+-vegan-version-646890'
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 26,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 47,
    healthScore: 10,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 86.57,
    id: 655308,
    title: 'Peanut Butter Filled Chocolate Cupcakes with Chocolate Ganache Frosting',
    readyInMinutes: 45,
    servings: 18,
    sourceUrl: 'http://www.foodista.com/recipe/K6ZQ2VLQ/peanut-butter-filled-chocolate-cupcakes-with-chocolate-ganache-frosting',       
    image: 'https://spoonacular.com/recipeImages/655308-312x231.jpg',
    imageType: 'jpg',
    summary: 'The recipe Peanut Butter Filled Chocolate Cupcakes with Chocolate Ganache Frosting could satisfy your American craving in approximately <b>45 minutes</b>. For <b>87 cents per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. This recipe makes 18 servings with <b>668 calories</b>, <b>18g of protein</b>, and <b>46g of fat</b> each. 1 person has made this recipe and would make it again. A mixture of fyi: the ganache needs hours to cool, butter, powdered sugar, and a handful of other ingredients are all it takes to make this recipe so yummy. All things considered, we decided this recipe <b>deserves a spoonacular score of 50%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/peanut-butter-cupcakes-with-bittersweet-chocolate-ganache-frosting-598554">Peanut Butter Cupcakes with Bittersweet Chocolate Ganache Frosting</a>, <a href="https://spoonacular.com/recipes/ganache-filled-chocolate-cupcakes-with-seven-minute-meringe-frosting-189918">Ganache-Filled Chocolate Cupcakes with Seven-Minute Meringe Frosting</a>, and <a href="https://spoonacular.com/recipes/4-layer-chocolate-brownie-cake-with-peanut-butter-frosting-and-chocolate-ganache-479736">4 Layer Chocolate Brownie Cake with Peanut Butter Frosting and Chocolate Ganache</a> for similar recipes.',
    cuisines: [ 'American' ],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [],
    occasions: [],
    analyzedInstructions: [ [Object] ],
    spoonacularSourceUrl: 'https://spoonacular.com/peanut-butter-filled-chocolate-cupcakes-with-chocolate-ganache-frosting-655308'      
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 1,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 47,
    healthScore: 9,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 40.88,
    id: 664625,
    title: 'Vegetable-Bean Chili',
    readyInMinutes: 45,
    servings: 26,
    sourceUrl: 'http://www.foodista.com/recipe/NDV6QWGL/vegetable-bean-chili',
    image: 'https://spoonacular.com/recipeImages/664625-312x231.jpg',
    imageType: 'jpg',
    summary: 'The recipe Vegetable-Bean Chili is ready <b>in approximately 45 minutes</b> and is definitely an excellent <b>gluten free',
    cuisines: [ 'American' ],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [ 'super bowl' ],
    analyzedInstructions: [ [Object] ],
    spoonacularSourceUrl: 'https://spoonacular.com/vegetable-bean-chili-664625'
  }
],
[
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 11,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 2,
    spoonacularScore: 74,
    healthScore: 27,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 81.67,
    id: 633185,
    title: 'Awesome! No Bake ~ Macaroni and Cheese',
    readyInMinutes: 45,
    servings: 16,
    sourceUrl: 'http://www.foodista.com/recipe/DJBXLXPJ/awesome-no-bake-macaroni-and-cheese',
    image: 'https://spoonacular.com/recipeImages/633185-312x231.jpg',
    imageType: 'jpg',
    summary: 'You can never have too many side dish recipes, so give Awesome! No Bake ~ Macaroni and Cheese a try. This recipe serves 16 and costs 82 cents per serving. One serving contains <b>338 calories</b>, <b>11g of protein</b>, and <b>21g of fat</b>. Only a few people made this recipe, and 2 would say it hit the spot. A mixture of ketchup, you favorite macaroni, cottage cheese, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 76%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/macaroni-and-cheese-home-made-macaroni-and-cheese-is-a-comfort-food-that-is-hard-to-beat-you-can-put-away-the-pre-packaged-macaroni-and-cheese-at-the-store-600947">Macaroni and Cheese – home made macaroni and cheese is a comfort food that is hard to beat. You can put away the pre packaged macaroni and cheese at the store</a>, <a href="https://spoonacular.com/recipes/no-bake-macaroni-cheese-695678">No-Bake Macaroni & Cheese</a>, and <a href="https://spoonacular.com/recipes/macaroni-cheese-bake-429937">Macaroni & Cheese Bake</a> for similar recipes.',
    cuisines: [ 'American' ],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [],
    occasions: [],
    spoonacularSourceUrl: 'https://spoonacular.com/awesome-no-bake-macaroni-and-cheese-633185',
    steps: [
      'Heat a large saucepot with a drizzle of olive oil and add the onion, garlic, bell pepper and cilantro and let saut until the onion is clear.',
      'Add the frozen creamed spinach and continue to saut until the spinach is thawed.',
      'Add the ketchup and stir, continuing to saut on low.In a food processor combine the cottage cheese, milk and 4 oz. of the shredded cheddar cheese. Process until the cottage is smooth.Prepare the macaroni as directed.',
      'Add the cooked macaroni to the saucepot with the sauting spinach and toss add the processed cottage cheese mixture and toss. Turn off heat. Top with the remaining 4 oz. of cheddar cheese. Cover and let the cheddar cheese melt. This takes only a second or two.'     
    ],
    equipment: [ 'pot', 'none', 'food processor', 'pot' ]
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 1,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 61,
    healthScore: 21,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 87.32,
    id: 1095892,
    title: 'Vegan Green Bean Casserole',
    readyInMinutes: 60,
    servings: 6,
    sourceUrl: 'https://www.foodista.com/recipe/2M3K34BV/green-bean-casserole-vegan',
    image: 'https://spoonacular.com/recipeImages/1095892-312x231.jpg',
    imageType: 'jpg',
    summary: `The recipe Vegan Green Bean Casserole is ready <b>in about 1 hour</b> and is definitely an awesome <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> option for lovers of American food. For <b>87 cents per serving</b>, this recipe <b>covers 12%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains around <b>5g of protein</b>, <b>3g of fat</b>, and a total of <b>110 calories</b>. This recipe serves 6. It will be a hit at your <b>Thanksgiving</b> event. This recipe from Foodista requires nutritional yeast, water, onion, and extra-virgin olive oil. 1 person were glad they tried this recipe. It works well as a very reasonably priced hor d'oeuvre. Overall, this recipe earns a <b>solid spoonacular score of 71%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/vegan-green-bean-casserole-589324">Vegan Green Bean Casserole</a>, <a href="https://spoonacular.com/recipes/vegan-green-bean-casserole-624815">Vegan Green Bean Casserole</a>, and <a href="https://spoonacular.com/recipes/vegan-green-bean-casserole-1397921">Vegan Green Bean Casserole</a>.`,
    cuisines: [ 'American' ],
    dishTypes: [
      'side dish',
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [ 'fall', 'thanksgiving', 'winter' ],
    spoonacularSourceUrl: 'https://spoonacular.com/vegan-green-bean-casserole-1095892',
    steps: [
      'In a wide-bottomed saucepan, add 1 tablespoon extra virgin coconut oil and set to low heat.',
      'Add the onions and cook for 30 minutes. Stir occasionally to caramelize. If the onions look dry, splash a bit of water into the pan.While waiting for the onions to cook, steam the parsnip. Set aside and let them cool.After that, prepare the green beans.',
      'Remove the ends of the beans and cut them into 2 inch pieces. Steam them for 8 minutes. Set them aside in an 8x8 baking dish.Once the onions have caramelized, set them aside. Cook the mushrooms in the same pan and saute for one minute.',
      'Add garlic. Stir for 5 minutes.',
      'Add half of the garlic and mushroom mixture to the green beans.Preheat the oven to 350 degrees Fahrenheit.',
      'Put the other half of the garlic and mushroom mixture, as well as the steamed parsnips in a blender.',
      'Add the nutritional yeast, salt, pepper, and crushed red pepper.',
      'Pour the blended mixture over the mushrooms and green beans. Stir to coat. Use the caramelized onions as toppings.',
      'Bake for another 30 minutes.',
      'Serve.'
    ],
    equipment: [
      'sauce pan',  'frying pan',
      'baking pan', 'none',
      'oven',       'blender',
      'none',       'none',
      'oven',       'none'
    ]
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 5,
    gaps: 'no',
    lowFodmap: false,
    preparationMinutes: 5,
    cookingMinutes: 35,
    aggregateLikes: 0,
    spoonacularScore: 58,
    healthScore: 15,
    creditsText: 'Jen West',
    sourceName: 'Pink When',
    pricePerServing: 81.27,
    id: 1416203,
    title: 'Tater Tot Chili Cheese Casserole',
    readyInMinutes: 40,
    servings: 6,
    sourceUrl: 'https://www.pinkwhen.com/tater-tot-chili-cheese-casserole/',
    image: 'https://spoonacular.com/recipeImages/1416203-312x231.jpg',
    imageType: 'jpg',
    summary: `The recipe Tater Tot Chili Cheese Casserole can be made <b>in around 40 minutes</b>. Watching your figure? This gluten free recipe has <b>171 calories</b>, <b>6g of protein</b>, and <b>10g of fat</b> per serving. For <b>81 cents per serving</b>, this recipe 
<b>covers 10%</b> of your daily requirements of vitamins and minerals. This recipe serves 6. It works well as an American hor d'oeuvre. 
It will be a hit at your <b>The Super Bowl</b> event. 1 person were impressed by this recipe. It is brought to you by Pink When. A mixture of chili, tater tots, cheddar cheese, and a handful of other ingredients are all it takes to make this recipe so delicious. All things considered, we decided this recipe <b>deserves a spoonacular score of 0%</b>. This score is improvable. <a href="https://spoonacular.com/recipes/chili-cheese-tater-tot-casserole-688250">Chili Cheese Tater Tot Casserole</a>, <a href="https://spoonacular.com/recipes/chili-tater-tot-casserole-138065">Chili Tater Tot Casserole</a>, and <a href="https://spoonacular.com/recipes/tater-tot-casserole-aka-tater-tot-hotdish-713801">Tater Tot Casserole (aka Tater Tot Hotdish)</a> are very similar to this recipe.`,
    cuisines: [ 'American' ],
    dishTypes: [
      'side dish',
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [ 'gluten free' ],
    occasions: [ 'super bowl', 'fall', 'winter' ],
    spoonacularSourceUrl: 'https://spoonacular.com/tater-tot-chili-cheese-casserole-1416203',
    steps: [
      'Heat oven to 35',
      'Add chili to cover the bottom of a casserole dish.',
      'Top the chili with frozen tater tots. Cook in oven for 20 minutes.',
      'Carefully top casserole with shredded cheese and cook for an additional 10 minutes or until cheese is melted.',
      'Serve.',
      'FREEZER MEAL INSTRUCTIONS',
      'Add the chili to a freezer safe container. Top with tater tots and remove as much air as possible before freezing. Leave in the freezer for up to 3 months.'
    ],
    equipment: [
      'oven',
      'casserole dish',
      'oven',
      'none',
      'none',
      'none',
      'none'
    ]
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 16,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 50,
    healthScore: 13,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 68.86,
    id: 646890,
    title: 'Home-Made Baked Corn Dogs + Vegan Version',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/43SL6B4C/home-made-baked-corn-dogs-vegan-version',
    image: 'https://spoonacular.com/recipeImages/646890-312x231.jpg',
    imageType: 'jpg',
    summary: `Home-Made Baked Corn Dogs + Vegan Version might be just the <b>American</b> recipe you are searching for. This hor d'oeuvre has <b>507 calories</b>, <b>17g of protein</b>, and <b>17g of fat</b> per serving. This recipe serves 4 and costs 69 cents per serving. This recipe from Foodista has 1 fans. Head to the store and pick up baking soda, , water, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. With a spoonacular <b>score of 49%</b>, this dish is solid. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/home-made-apple-butter-with-baked-brie-523639">Home Made Apple Butter with Baked Brie</a>, <a href="https://spoonacular.com/recipes/baked-corn-dogs-136170">Baked Corn Dogs</a>, and <a href="https://spoonacular.com/recipes/baked-corn-dogs-568330">Baked corn dogs</a>.`,
    cuisines: [ 'American' ],
    dishTypes: [
      'fingerfood',   'lunch',
      'antipasti',    'main course',
      'starter',      'snack',
      'appetizer',    'main dish',
      'antipasto',    'dinner',
      "hor d'oeuvre"
    ],
    diets: [],
    occasions: [],
    spoonacularSourceUrl: 'https://spoonacular.com/home-made-baked-corn-dogs-+-vegan-version-646890',
    steps: [
      'Heat oven to 375 F. Line a baking sheet with parchment paper and set aside.',
      'In a medium-sized mixing bowl, sift together the cornmeal, flour, sugar, baking powder, baking soda salt and mustard powder, and make a well in the center. In another bowl, whisk together the milk, the egg and the oil until well combined.',
      'Add to the well in the dry ingredients and mix until just combined.',
      'Insert a stick into each of the hot dog half. Dip each hot dog into the flour, then shake of excess with one hand. Wet the other hand, grab some batter and spread it out in your hand into a somewhat square or rectangle, and place the hotdog right in the middle, turning to cover.',
      'Place on the prepared bake sheet.',
      'Bake for 15 to 20 minutes, or until puffed and golden brown.',
      'Also, you can make this into a vegan version, by replacing the egg with egg substitute, wieners with soydogs, and milk with almond milk.'
    ],
    equipment: [
      'baking paper',
      'mixing bowl',
      'none',
      'none',
      'oven',
      'oven',
      'none'
    ]
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 26,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 47,
    healthScore: 10,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 86.57,
    id: 655308,
    title: 'Peanut Butter Filled Chocolate Cupcakes with Chocolate Ganache Frosting',
    readyInMinutes: 45,
    servings: 18,
    sourceUrl: 'http://www.foodista.com/recipe/K6ZQ2VLQ/peanut-butter-filled-chocolate-cupcakes-with-chocolate-ganache-frosting',       
    image: 'https://spoonacular.com/recipeImages/655308-312x231.jpg',
    imageType: 'jpg',
    summary: 'The recipe Peanut Butter Filled Chocolate Cupcakes with Chocolate Ganache Frosting could satisfy your American craving in approximately <b>45 minutes</b>. For <b>87 cents per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. This recipe makes 18 servings with <b>668 calories</b>, <b>18g of protein</b>, and <b>46g of fat</b> each. 1 person has made this recipe and would make it again. A mixture of fyi: the ganache needs hours to cool, butter, powdered sugar, and a handful of other ingredients are all it takes to make this recipe so yummy. All things considered, we decided this recipe <b>deserves a spoonacular score of 50%</b>. This score is solid. Try <a href="https://spoonacular.com/recipes/peanut-butter-cupcakes-with-bittersweet-chocolate-ganache-frosting-598554">Peanut Butter Cupcakes with Bittersweet Chocolate Ganache Frosting</a>, <a href="https://spoonacular.com/recipes/ganache-filled-chocolate-cupcakes-with-seven-minute-meringe-frosting-189918">Ganache-Filled Chocolate Cupcakes with Seven-Minute Meringe Frosting</a>, and <a href="https://spoonacular.com/recipes/4-layer-chocolate-brownie-cake-with-peanut-butter-frosting-and-chocolate-ganache-479736">4 Layer Chocolate Brownie Cake with Peanut Butter Frosting and Chocolate Ganache</a> for similar recipes.',
    cuisines: [ 'American' ],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [],
    occasions: [],
    spoonacularSourceUrl: 'https://spoonacular.com/peanut-butter-filled-chocolate-cupcakes-with-chocolate-ganache-frosting-655308',     
    steps: [
      'How Tos:Frosting:I suggest starting by making your ganache first because it takes some time to cool to room temp.In a medium-large sized microwave safe bowl heat heavy cream until it SIMMERS not boils. About 3-4 minutes',
      'Pour chocolate chips into a food processor.',
      'Add the hot cream.Process until creamy.Set aside until it cools to room temperature. About 2 hours',
      'Cupcakes:Preheat the oven to 350 degrees F.Line cupcake pans with paper liners.In the bowl of an electric mixer fitted with a paddle attachment, cream the butter and 2 sugars on high speed until light and fluffy, approximately 5 minutes.Lower the speed to medium, add the eggs 1 at a time,',
      'Add the vanilla and mix well.In a separate bowl, whisk together the buttermilk, sour cream, and coffee.In another bowl, sift together the flour, cocoa, baking soda, and salt.On low speed, add the buttermilk mixture and the flour mixture alternately in thirds to the mixer bowl, beginning with the buttermilk mixture and ending with the flour mixture.',
      'Mix only until blended.Fold the batter with a rubber spatula to be sure its completely blended.',
      'Pour batter into cupcake pan so each cup is filled about  of the way. I used a gravy ladle and it was almost just enough.',      
      'Bake for 20-25 minutes or until toothpick comes out clean.Cool on wire rack.Pb Filling:In a medium mixing bowl combine softened butter and peanut butter and beat on medium-low.',
      'Add sifted powdered sugar and continue to beat mixture until smooth and blended.',
      'Add to a frosting bag with tip.Set aside.Ganache Frosting Final Step:Once ganache has cooled to room temperature add to a standing mixer bowl and whisk on high until the frosting is light and fluffy.',
      'Transfer to a tipped frosting bag and set aside.Assembling the cupcakes:Once cupcakes have cooled fill each cupcake with pb filling by inserting tip of bag into center of cupcake and lightly squeezing the frosting bag.The top of the cupcake with expand slightly.Repeat until each cupcake is filled.Frost each cupcake by slowly squeezing the bag with the tip slightly touching the cupcake. You can either spin the cupcake or move your bag creating a spiral around the perimeter of the cupcake working your way to the center.Top with chopped salted peanuts (optional)Enjoy!!!My Chocolate cupcake recipe came from one of the best bakers ever Ina Garten'
    ],
    equipment: [
      'microwave',
      'food processor',
      'none',
      'hand mixer',
      'blender',
      'spatula',
      'muffin tray',
      'mixing bowl',
      'none',
      'blender',
      'none'
    ]
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 1,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 47,
    healthScore: 9,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 40.88,
    id: 664625,
    title: 'Vegetable-Bean Chili',
    readyInMinutes: 45,
    servings: 26,
    sourceUrl: 'http://www.foodista.com/recipe/NDV6QWGL/vegetable-bean-chili',
    image: 'https://spoonacular.com/recipeImages/664625-312x231.jpg',
    imageType: 'jpg',
    summary: 'The recipe Vegetable-Bean Chili is ready <b>in approximately 45 minutes</b> and is definitely an excellent <b>gluten free',
    cuisines: [ 'American' ],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre"
    ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [ 'super bowl' ],
    spoonacularSourceUrl: 'https://spoonacular.com/vegetable-bean-chili-664625',
    steps: [
      'The following recipe is one of my favorites. It is modified very little lowfat, but easily adaptable).In a large pot, saute over medium heat the onion, carrots, celery, bell pepper and garlic until softened, about 7 minutes.',
      'Add the spices and stir for 30 seconds. Stir in the beans, tomato sauce, tomatoes, and vegetable stock. Cook, partially covered,  until thickened, about 20 minutes. Stir in the corn and cook for 5 minutes.',
      'Remove bay leaves and serve.One good way to serve the chili is with tortillas, salsa and sour cream.'
    ],
    equipment: [ 'pot', 'none', 'none' ]
  }
];
